site_name: Monitor Resource Based Access Control Lab - Gateway Restrictions
site_url: https://ibm.github.io/maximo-labs/
site_author: Kajal Lalwani
site_description: "Maximo Monitor 9.2 Resource Based Access Control Lab - Gateway Restrictions"
site_dir: ../../site/monitor_resource_based_access_control_9.2

nav:
  - Get back to Maximo Labs: ..
  - Monitor RBAC 9.2 Lab:
    - Welcome: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
        - 1. Gateway Restrictions: gateway_restrictions.md

  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

extra_css:
  - css/extra.css
extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.js
  - js/extra.js

markdown_extensions:
  - attr_list
  - admonition

# Made with Bob
