site_name: Maximo APM V8.7 Hands On Lab
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Carlos Ferreira & Contributors
site_description: "Maximo Asset Performance Management v8.7 Hands on Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site/apm_8.7

nav:
  - Get back to Maximo Labs: /
  - Maximo APM V8.7.0 Lab:
    - Welcome to the Lab: index.md
    - Get Started: get_started.md
    - Pre-Requisites: prereqs.md
  - Exercises:
      - Setup Watson Studio for Predict: setup_watson_studio.md
      - Setup Local Python Environment : setup_local_environment.md
      - Setup Assets Using Python: dataload_python.md
      - Understand Health and Predict - Utilities Models: hpu_models.md
      - Install and Configure App Connect: appconnect_install.md
      - Setup Asset Data Load With App Connect: dataload_appconnect.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition