site_name: Monitor Live Demo Asset Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Jan Ekstrøm
site_description: "Maximo Monitor Live Demo Asset Hands on Lab"
site_dir: ../../site/monitor_live_demo_asset

nav:
  - Get back to Maximo Labs: ..
  - Monitor Live Demo Asset Lab:
    - Welcome to this lab: index.md
    - Pre-Requisites: prereqs.md
    - RPE User Guide: user_guide.md
  - Exercises:
    - 1. Create Monitor devices: create_devices.md
    - 2. Prepare Rasperry Pi: prepare_pi.md
    - 3. Convert Pi to RPE: convert_pi.md
    - 4. Verify RPE is working: verify_rpe.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright
  

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

extra_css:
  - css/extra.css
extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.js
  - js/extra.js

markdown_extensions:
  - attr_list
  - admonition