site_name: Edge Data Collector Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Jan Ekstrøm & Contributors
site_description: "Maximo Monitor Edge Data Collector Hands on Lab"
site_dir: ../../site/edc_8.11

nav:
  - Get back to Maximo Labs: ..
  - Monitor Edge Data Collector Lab:
    - Welcome: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
        - 1. Setup Simulator Environment: setup.md
        - 2. Create Monitor Devices: monitor_devices.md
        - 3. Create EDC Integration: edc_integration.md
        - 4. Deploy and verify integration: deploy.md
        - 5. Create Monitor metric: monitor_metrics.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - ../css/extra.css

extra_javascript:
  - ../js/popper.min.js
  - ../js/tippy-bundle.umd.js
  - ../js/clipboard.js
  - ../js/extra.js

google_analytics: ['G-EGH6ZGZ8CT', 'maximo-labs']