site_name: Maximo v9.0 APM Hands On Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Carlos Ferreira & Contributors
site_description: "Maximo Asset Performance Management v9 Hands on Lab"
site_dir: ../../site/apm_9.0

nav:
  - Get back to Maximo Labs: ..
  - Maximo Health and Predict Lab:
    - Welcome to this lab: index.md
    - Get Started: get_started.md
    - Pre-Requisites: prereqs.md
  - Exercises:
      - Setup Health and Predict Demonstration: build_demo.md
      - Health and Predict Overview Task Guide: demo_script.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright
  

theme:
  name: readthedocs
  analytics:
    gtag: G-EGH6ZGZ8CT
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - ../css/extra.css

extra_javascript:
  - ../js/popper.min.js
  - ../js/tippy-bundle.umd.js
  - ../js/clipboard.js
  - ../js/extra.js
