site_name: MAS 9.0 Overview Lab
site_url: https://ibm.github.io/maximo-labs/
site_author: Carlos Ferreira & Contributors
site_description: "Maximo Application Suite 9.0 Overview Hands on Lab"
site_dir: ../../site/mas_9.0

nav:
  - Get back to Maximo Labs: ..
  - MAS 9.0 Overview Labs:
    - Welcome: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
    - 1. Reliability Strategies: demo-rsl.md
    - 2. Monitor: demo-monitor.md
    - 3. Visual Inspection: demo-mvi.md
    - 4. Manage: demo-manage.md
    - 5. Mobile: demo-mobile-assist.md
    - 6. Health - Predict: demo-health-predict.md
    - 7. Closing: closing.md 
    - Lab Clean up: clean.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - ../css/extra.css

extra_javascript:
  - ../js/popper.min.js
  - ../js/tippy-bundle.umd.js
  - ../js/clipboard.js
  - ../js/extra.js

google_analytics: ['G-EGH6ZGZ8CT', 'maximo-labs']