site_name: Visual Inspection SaaS Labs
site_url: https://ibm.github.io/maximo-labs/
site_author: Cecilia Stark & Contributors
site_description: "Visual Inspection SaaS Hands on Lab"
site_dir: ../../site/mvi_saas

nav:
  - Get back to Maximo Labs: ..
  - MVI SaaS Lab:
    - Welcome to the MVI Lab: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
    - 1.1 DataSets: exercise1-1.md
    - 1.2 Train and Deploy Model: exercise1-2.md
    - 1.3 Create Project: exercise1-3.md
    - 2.1 Create Inspection: exercise2-1.md
    - 2.2 Conduct Inspection: exercise2-2.md
    - 2.3 Dashboard Configuration: exercise2-3.md
    - Next Steps: nextsteps.md
    - Troubleshooting: troubleshoot.md
  - About:
    - Release Notes: release_notes.md
    - Copyright: ../copyright

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition