site_name: Maximo APM Hands On Lab
site_url: http://maximo-lab.monitordemo4.ibmmam.com/
site_author: Carlos Ferreira & Contributors
site_description: "Maximo Asset Performance Management v8.11 Hands on Lab"
site_dir: ../../site/apm_8.11

nav:
  - Get back to Maximo Labs: /
  - Maximo Health and Predict Lab:
    - Welcome to the Lab: index.md
    - Get Started: get_started.md
    - Pre-Requisites: prereqs.md
  - Exercises:
      - Setup Health and Predict Demonstration: build_demo.md
      - Health and Predict Overview Task Guide: demo_script.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition