site_name: Maximo Application Suite Deployment Labs
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Arif Ali
site_description: "Maximo Application Suite 8.5 on Red Hat OpenShift Kubernetes Services (ROKS) in IBM Cloud"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site/ocp_8.5

nav:
  - Get back to Maximo Labs: /
  - OCP Labs:
    - Welcome to the MAS Deployment Labs: index.md
    - Get Started: getting_started.md
    - Pre-Requisites: prereqs.md
    - Exercises:
        - 1. Dependency - MongoDB: dependency-mongodb.md
        - 2. Dependency - Cert Manager: dependency-certmanager.md
        - 3. Dependency - BAS: dependency-bas.md
        - 4. Dependency - SLS: dependency-sls.md
        - 5. MAS Core: mas-core.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition
