site_name: MAS Overview 8.5 Labs
site_url: https://mam-hol.eu-gb.mybluemix.net/
site_author: Carlos Ferreira & Contributors
site_description: "Maximo Application Suite Overview 8.5 Overview Hands on Lab"
google_analytics: ['UA-159649729-1', 'auto']
site_dir: ../../site/mas_8.5

nav:
  - Get back to Maximo Labs: /
  - MAS Overview 8.5 Labs:
    - Welcome to the Maximo Application Suite Overview 8.5 Overview Lab: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
    - 1. Monitor - MVI: demo-monitor-mvi.md
    - 2. DTX - MVI: demo-dtx-mon-mvi.md
    - 3. DTX - Manage: demo-dtx-manage.md
    - 4. Mobile: demo-mobile-assist-safe.md
    - 5. Safety: demo-safety.md
    - 6. Health - Predict: demo-health-predict.md
    - 7. Closing: closing.md
  - Lab Clean up: clean.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition